name: Retrieve latest icons from excel file

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  main:
    runs-on: windows-latest
    env:
        TOLGEE_KEY: "${{ secrets.TOLGEE_TOKEN }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download icons json file
        run: |
          pythion -m pip install xlrd
          cd WebBasedData
          git config user.email "excelbot@github.com"
          git config user.name "Excel Bot"
          python generate_json_from_excel.py 
          git commit screenshot-database.json -m "Update icons and screenshots"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          base: main
          title: "Update icons and screenshots from the excel file"
          reviewers: "${{ github.repository_owner }}"
          author: "Excel Bot <excel-bot@users.noreply.github.com>"
          commit-message: "Update icons and screenshots from the excel file"
          branch: pull-request/update-translation
